# https://github.com/zalando/zappr/blob/master/.zappr-example.yml
approvals:
  minimum: 2
  # approval = comment that matches this regex
  pattern: "^(:\\+1:|👍|LGTM|lgtm)$"
  from:
    # commenter must be either one of:
    # a public zalando org member
    orgs:
      - zalando
X-Zalando-Team: bus
X-Zalando-Type: code
