# https://github.com/zalando/zappr/blob/master/.zappr-example.yml
approvals:
  # PR needs at least 4 approvals
  minimum: 1
  # approval = comment that matches this regex
  pattern: "^(:\\+1:|👍|LGTM|lgtm)$"
  from:
    # commenter must be either one of:
    # a public zalando org member
    orgs:
      - zalando
