version: "2017-09-20"
pipeline:
  - id: build
    type: script
    commands:
      - desc: "setup the environment"
        cmd: |
          apt-get update
          apt-get install -y python3-dev python-pip python3-pip
          curl -sSL https://delivery.cloud.zalando.com/utils/ensure-docker | sh
          sudo update-alternatives --install /usr/bin/python python /usr/bin/python3 10
          pip install -r python/requirements.txt
  - id: run-test
    type: script
    commands:
      - desc: "run tests"
        cmd: |
          nosetests -w python