version: "2017-09-20"

dependencies:
  - id: python
    type: docker
    ref: registry.opensource.zalan.do/library/python-3.8

pipeline:
  - id: test
    overlay: ci/python
    type: script
    commands:
      - desc: "setup the environment"
        cmd: |
          apt-get update
          apt-get install -qy python3-dev python-pip python3-pip
          update-alternatives --install /usr/bin/python python /usr/bin/python3 10
          pip install -r python/requirements.txt
      - desc: "run tests"
        cmd: |
          nosetests -w python
